services: mongodb
language: node_js
node_js:
    - '14'
addons:
    code_climate:
        repo_token: 0728f4b6cae40a3c8e5b73076e24006a449f72513ac40d029efd78bffae486b4
after_script:
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter <  ./coverage/lcov.info
